# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\source\Hello_World\TemeratureApp\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 647)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.currentTemperatureLabel = QtWidgets.QLabel(self.centralwidget)
        self.currentTemperatureLabel.setGeometry(QtCore.QRect(10, 20, 141, 20))
        self.currentTemperatureLabel.setObjectName("currentTemperatureLabel")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(10, 80, 101, 26))
        self.dateEdit.setDate(QtCore.QDate(2000, 1, 6))
        self.dateEdit.setObjectName("dateEdit")
        self.btn_getTemperatureData = QtWidgets.QPushButton(self.centralwidget)
        self.btn_getTemperatureData.setGeometry(QtCore.QRect(120, 80, 93, 29))
        self.btn_getTemperatureData.setObjectName("btn_getTemperatureData")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 781, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dateTimeEdit_startDate = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit_startDate.setGeometry(QtCore.QRect(10, 130, 194, 26))
        self.dateTimeEdit_startDate.setObjectName("dateTimeEdit_startDate")
        self.dateTimeEdit_endDate = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit_endDate.setGeometry(QtCore.QRect(230, 130, 194, 26))
        self.dateTimeEdit_endDate.setObjectName("dateTimeEdit_endDate")
        self.btn_getPeriodTemperatureData = QtWidgets.QPushButton(self.centralwidget)
        self.btn_getPeriodTemperatureData.setGeometry(QtCore.QRect(440, 130, 93, 29))
        self.btn_getPeriodTemperatureData.setObjectName("btn_getPeriodTemperatureData")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 874, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.currentTemperatureLabel.setText(_translate("MainWindow", "Current Temperature:"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy"))
        self.btn_getTemperatureData.setText(_translate("MainWindow", "Get stats"))
        self.dateTimeEdit_startDate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy HH:mm"))
        self.dateTimeEdit_endDate.setDisplayFormat(_translate("MainWindow", "dd.MM.yyyy HH:mm"))
        self.btn_getPeriodTemperatureData.setText(_translate("MainWindow", "Get stats"))